version: '3'
services:
  openhab:
    image: "openhab/openhab:3.0.1"
    container_name: openHAB-server
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.17.5.2
    ports:
      - 8080:80
      - 8443:443
      - 5007:5007
      - 8101:8101
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../services/openhab/addons:/openhab/addons
      - ../services/openhab/config:/openhab/conf
      - ../services/openhab/userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: "80"
      OPENHAB_HTTPS_PORT: "443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Africa/Johannesburg"
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://172.17.5.2:8080"]
      interval: 30s
      timeout: 10s  
      retries: 6
  
  MQTT-broker:
    image: eclipse-mosquitto
    container_name: openhab-mosquitto-broker
    restart: unless-stopped
    networks:
      openhab_network:
        ipv4_address: 172.17.5.3
    ports:
      - 1883:1883
    volumes:
      - ../services/mosquitto/config:/mosquitto/config
      - ../services/mosquitto/data:/mosquitto/data
      - ../services/mosquitto/logs:/mosquitto/logs

networks:
  openhab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.5.0/16
          gateway: 172.17.5.1
